[versions]
paper-api = "1.21.11-R0.1-SNAPSHOT"
ccutils = "726f19c60a"
floodgate = "2.2.5-SNAPSHOT"
configurate-yaml = "4.2.0"
worldedit = "7.3.18"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
ccutils = { module = "com.github.andrew121410.CCUtilsJava:ccutilsjava-bukkit", version.ref = "ccutils" }
floodgate = { group = "org.geysermc.floodgate", name = "api", version.ref = "floodgate" } # https://github.com/GeyserMC/Floodgate/blob/master/gradle.properties
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate-yaml" }
worldedit-core = { group = "com.sk89q.worldedit", name = "worldedit-core", version.ref = "worldedit" }
worldedit-bukkit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldedit" }

[plugins]
shadow-plugin = { id = "com.gradleup.shadow", version = "9.3.1" } # https://github.com/GradleUp/shadow
blossom = { id = "net.kyori.blossom", version = "2.2.0" } # https://github.com/KyoriPowered/blossom